import { defineConfig } from "tsup";

export default defineConfig({
  entry: {
    index: "src/entries/index.ts",
    runtime: "src/entries/runtime.ts",
    "hosting/ef": "src/entries/hosting-ef.ts",
    "hosting/gr": "src/entries/hosting-gr.ts",
    "network-service/ef": "src/entries/network-service-ef.ts",
    "network-service/gr": "src/entries/network-service-gr.ts",
    "transit/ef": "src/entries/transit-ef.ts",
    "transit/gr": "src/entries/transit-gr.ts",
    "access/ef": "src/entries/access-ef.ts",
    "access/gr": "src/entries/access-gr.ts",
    "data/hosting-ef": "src/entries/data/hosting-ef.ts",
    "data/hosting-gr": "src/entries/data/hosting-gr.ts",
    "data/network-service-ef": "src/entries/data/network-service-ef.ts",
    "data/network-service-gr": "src/entries/data/network-service-gr.ts",
    "data/transit-ef": "src/entries/data/transit-ef.ts",
    "data/transit-gr": "src/entries/data/transit-gr.ts",
    "data/access-ef": "src/entries/data/access-ef.ts",
    "data/access-gr": "src/entries/data/access-gr.ts",
  },
  format: ["esm", "cjs"],
  dts: true,
  clean: true,
  splitting: false,
  sourcemap: false,
  target: "es2020",
  outDir: "lib",
});
