const fs = require("node:fs");
const path = require("node:path");

const ROOT = path.join(__dirname, "..");
const DIST = path.join(ROOT, "dist");
const GENERATED = path.join(ROOT, "src", "generated");
const FORMAT_VERSION = 1;

function readPackage() {
  return JSON.parse(fs.readFileSync(path.join(ROOT, "package.json"), "utf8"));
}

function readHeader(filename) {
  const b64 = fs.readFileSync(path.join(DIST, filename), "utf8").trim();
  const buf = Buffer.from(b64, "base64");
  return {
    b64,
    bytes: buf.length,
    offset: buf.readUInt32LE(0),
    count: buf.readUInt32LE(4),
    range: buf.readUInt32LE(8),
    k: buf.readUInt8(12),
    l: buf.readUInt8(13),
  };
}

function dataDateFromVersion(version) {
  const [, , yyyymmdd] = /^(\d+)\.(\d{8})\.(\d+)$/.exec(version) || [];
  if (!yyyymmdd) return new Date().toISOString().slice(0, 10);
  return `${yyyymmdd.slice(0, 4)}-${yyyymmdd.slice(4, 6)}-${yyyymmdd.slice(6, 8)}`;
}

function writeModule(filename, constant, value) {
  fs.writeFileSync(
    path.join(GENERATED, filename),
    `// Generated by scripts/generate-modules.cjs. Do not edit manually.\nexport const ${constant} = ${JSON.stringify(value)};\n`,
  );
}

function datasetMetadata(kind, encoding, header, rawFile) {
  return {
    kind,
    encoding,
    rawFile,
    bytes: header.bytes,
    offset: header.offset,
    count: header.count,
    range: header.range,
    minASN: header.offset,
    maxASN: header.offset + header.range - 1,
    k: header.k,
    l: header.l,
  };
}

function main() {
  const pkg = readPackage();
  fs.mkdirSync(GENERATED, { recursive: true });

  const definitions = [
    { kind: "hosting", file: "hosting", constant: "HOSTING" },
    {
      kind: "network_service",
      file: "network-service",
      constant: "NETWORK_SERVICE",
    },
    { kind: "transit", file: "transit", constant: "TRANSIT" },
    { kind: "access", file: "access", constant: "ACCESS" },
  ];
  const datasets = {};

  for (const definition of definitions) {
    const gr = readHeader(`${definition.file}.gr.b64`);
    const ef = readHeader(`${definition.file}.ef.b64`);
    writeModule(
      `${definition.file}-gr.ts`,
      `${definition.constant}_GR_B64`,
      gr.b64,
    );
    writeModule(
      `${definition.file}-ef.ts`,
      `${definition.constant}_EF_B64`,
      ef.b64,
    );
    datasets[`${definition.file.replace(/-([a-z])/g, (_, c) => c.toUpperCase())}GR`] =
      datasetMetadata(
        definition.kind,
        "gr",
        gr,
        `dist/${definition.file}.gr.b64`,
      );
    datasets[`${definition.file.replace(/-([a-z])/g, (_, c) => c.toUpperCase())}EF`] =
      datasetMetadata(
        definition.kind,
        "ef",
        ef,
        `dist/${definition.file}.ef.b64`,
      );
  }

  const metadata = {
    dataVersion: dataDateFromVersion(pkg.version),
    formatVersion: FORMAT_VERSION,
    packageVersion: pkg.version,
    datasets,
  };

  fs.writeFileSync(
    path.join(GENERATED, "metadata.ts"),
    [
      "// Generated by scripts/generate-modules.cjs. Do not edit manually.",
      `export const DATA_VERSION = ${JSON.stringify(metadata.dataVersion)};`,
      `export const FORMAT_VERSION = ${metadata.formatVersion};`,
      `export const PACKAGE_VERSION = ${JSON.stringify(metadata.packageVersion)};`,
      `export const DATASETS = ${JSON.stringify(metadata.datasets, null, 2)} as const;`,
      "",
    ].join("\n"),
  );

  console.log("Generated data modules.");
}

main();
